name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install node dependancies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Build docs
        run: npm run build
